support set console level separately
sofastack/sofa-common-tools pull request #143
Opened 2021-08-21 07:54 UTC by dkisser

### Motivation:

Explain the context, and why you're making that change.
To make others understand what is the problem you're trying to solve.

### Modification:

Describe the idea and modifications you've done.

### Result:

Fixes #<GitHub issue number>. 

If there is no issue then describe the changes introduced by this PR.

支持单独配置终端日志级别 #134

2021-08-30 06:49 UTC, alaneuler requested changes

2021-08-30 06:49 UTC, alaneuler commented on src/test/java/com/alipay/sofa/common/log/LoggerSpaceFactoryLogbackBuilderTest.java
> +        logger.warn("warn info===");
没有看到关于 console log 的相关测试呢？

应该得有 logger 是 info，但是 console appender 是 warn 的。
logger info 能在文件中打印出日志，但是 console appender 是不打印到终端的。

2021-09-03 07:43 UTC, alaneuler commented
@dkisser 看一下 review 的反馈哈～

2021-09-03 13:58 UTC, dkisser commented
> @dkisser 看一下 review 的反馈哈～

抱歉，现在才处理。我在修改的过程中发现一个问题，在Log4j2LoggerSpaceFactory构造函数中会完成appender的构造。在这里会在LoggerContext里面放一个上下文过滤器，这个过滤器在每次调用Logger实例时都会调用这个过滤器，第一次调用这个过滤器时我们会判断是否需要添加CONSOLE-appender，并完成appender先关的添加工作。在现有的版本中会判断loggerLevel与consoleLevel的大小，若是loggerLevel大于consoleLevel则会将当前logger的level设置成入参level。这里有问题，若是设置logger的Level为info，console的等级为warn，紧接着我们调用logger.isErrorable()，此时会调用LoggerContext的过滤器去将CONSOLE-APPENDER添加，但与此同时也会将logger的level设为Error，导致后续的Logger行为会受到影响。
![image](https://user-images.githubusercontent.com/24600271/132016111-ef4cdd11-5e4f-4bf5-841b-b4fb9409c2d8.png)
我认为这里肯定不能将LoggerLevel设置成调用的level,而本身我们是想将logger的日志级别与console appender的日志级别隔离开，所以我认为这里设为console level也不合理。因此，我认为删掉这部分代码最合适，删除后如下所示。

![image](https://user-images.githubusercontent.com/24600271/132017302-72d913a6-dccb-4add-8fbd-ecc0ac63eb40.png)

2021-09-23 07:04 UTC, alaneuler commented
@dkisser 抱歉，我的回复也慢了（异步 review 一般都这样 😛 ），你发现的这个地方的确是个 bug，可以按照你上面说的改掉～

但是你这种改法还是没有实现这个需求一开始想要的效果。
例如：logger 的级别是 INFO，但是这个 consoleAppender 的 level 是 WARN，也就是说 logger 原来所对应的 appender 还是按照原来的行为打印，但是打印到终端需要额外的级别判断，INFO 级别的日志不打印到终端。

2021-10-01 12:20 UTC, dkisser commented
> @dkisser 抱歉，我的回复也慢了（异步 review 一般都这样 stuck_out_tongue ），你发现的这个地方的确是个 bug，可以按照你上面说的改掉～
> 
> 但是你这种改法还是没有实现这个需求一开始想要的效果。 例如：logger 的级别是 INFO，但是这个 consoleAppender 的 level 是 WARN，也就是说 logger 原来所对应的 appender 还是按照原来的行为打印，但是打印到终端需要额外的级别判断，INFO 级别的日志不打印到终端。

这里我就没有太多思路了，因为我了解到的是目前可以通过对appender设置filter来改变appender的日志打印行为，但是似乎没有办法对appender单独设置日志等级。你这边有什么好的思路吗？

2021-11-03 07:01 UTC, merged