Add LegacySpringBanUtil
sofastack/sofa-common-tools pull request #180
Opened 2023-05-29 09:28 UTC by HzjNeverStop

### Motivation:

Explain the context, and why you're making that change.
To make others understand what is the problem you're trying to solve.

### Modification:

Describe the idea and modifications you've done.

### Result:

Fixes #<GitHub issue number>. 

If there is no issue then describe the changes introduced by this PR.

2023-05-29 09:42 UTC, ujjboy requested changes

2023-05-29 09:42 UTC, ujjboy commented on src/main/java/org/springframework/beans/LegacySpringBeanUtil.java
> +import org.springframework.util.ClassUtils;
这个6 的 classutils 和 5 的 BeanUtils 一定兼容吗？

2023-05-29 09:42 UTC, ujjboy commented on src/main/java/org/springframework/beans/LegacySpringBeanUtil.java
> +public class LegacySpringBeanUtil {
既然是复制的，Util 后面还是加个 s 吧

2023-05-29 09:45 UTC, HzjNeverStop commented on src/main/java/org/springframework/beans/LegacySpringBeanUtil.java
> +import org.springframework.util.ClassUtils;
仅使用了 Classutils.isAssignable 方法，这个方法spring4/5/6的实现是一样的

2023-05-29 09:46 UTC, HzjNeverStop commented on src/main/java/org/springframework/beans/LegacySpringBeanUtil.java
> +public class LegacySpringBeanUtil {
类名不是复制的，因此和 sofa-common-tools 的其他工具类命名风格保持一致，同时使用 Legacy 开头说明语义。

2023-05-30 02:15 UTC, ujjboy approved these changes

2023-05-30 02:18 UTC, merged